services:                  #サービスについて定義する。
  nginx:                   #nginxについて定義するという宣言。
    image: nginx       #イメージ名を指定
    container_name: "Docker-Practice"  #コンテナ名を指定
    ports:                 #ポート公開内容を指定する。
      - "80:80"          #コンテナ側で80だとホスト側で8080となる。
    volumes:               #ホストのフォルダをコンテナに追加する。 ホスト側:コンテナ側
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf  #コンフィグファイルをコピー
      - ./nginx/src/tgit-repo:/usr/share/nginx/html         #ソースをコピー